export function handleFailure(err: Error) {
  console.log(err.message);
}
